### ISSUE TITLE
About Form Join Elements

### ISSUE THREAD

**Issue by Qingqing-520** [QingQing-520/MySQLconnect#2]
In this exercise, can elements be added to the table only once? Is there a way to delete some elements after forgetting to add them, and then add them again?

**Comment by QingQing-520** [comment]
>

**Comment by Kalvin520** [comment]
> In this exercise, can elements be added to the table only once? Is there a way to delete some elements after forgetting to add them, and then add them again?

It should be possible but I didn't implement this function in the copy exercise but this gave me a good idea!
